### ISSUE TITLE
Get probabilities of predicted labels

### ISSUE THREAD

**Issue by tianke0711** [exelban/tensorflow-cifar-10#2]
1) The code is to predict the labels of test images. I want to ask you that how to predict the probabilities of each class in test images.

2) I want to use the code to predict the probabilities of new data's labels, how to save and load the model we have trained which used the train data.

Thanks!

**Comment by exelban** [comment]
@tianke0711 hi. I read Your email. I will response in free time.

**Comment by tianke0711** [comment]
@exelban  thanks for your kind response! I am waiting for your response!
